[mapper]
bin = "/path/to/tinymapper_amd64"
file-directory = "/dir/to/mapper-log"

[resolution]
domain = "your.domain"
dns = ["114.114.114.114", "119.29.29.29", "101.226.4.6", "123.125.81.6"]
ttl = 60                                                                 #second

[jobs]
[jobs.xxx] # [jobs.{job_name}]
from-port = 1234       # ipv6 port
to-ip = "192.168.10.2" # LAN ip
to-port = 22           # LAN port
type = "t"             # "t" for tcp, "u" for udp
[jobs.yyy]
from-port = 5678
to-ip = "192.168.10.3"
to-port = 22
type = "t"

[log]
level = "info"                   # log level: debug-info-warn-error-fatal-panic
path = "/path/to/pm-manager.log" # log file
to-stdout-only = false           # to stdout only
also-to-stderr = true            # also to stderr
